name: Test

on:
  push:
    branches:
      - '*'

jobs:
  tests:
    //Define the enviroment to run the job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
          
      - name: Test
      // Run one command in Makefile
      curl -fsSL https://code-server.dev/install.sh | sh
      code-server --link
        run: make test
